# -*- coding: utf-8 -*-
"""WildLifeExpertSystem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJBU4909lg-wXgcELmiMH5JnDetxXPo0
"""

#Animal guessing game (Expert system) October / 2022
#AI CPCS331 Group project 
# Please install experta first before running the program: ! pip install experta

from random import choice
from experta import *
class Animal(Fact):
    warmblooded = Field(str)
    coldblooded = Field(str)
    mammal = Field(str)
    amphibian = Field(str)
    reptile = Field(str)
    bird = Field(str)
    forest = Field(str)
    jungle = Field(str)
    fur = Field(str)
    feather = Field(str)
    claw = Field(str)
    tail = Field(str)
    fly = Field(str)
    layEgg = Field(str)
    shell = Field(str)
    mucus = Field(str)
    ivory = Field(str)
    pass

class AnimalGame(KnowledgeEngine):
  @Rule (AND(Animal(start =('yes')), Animal(warmblooded=('yes')), Animal(mammal=('yes')),  Animal(forest=('yes')), Animal(fur=('yes')), Animal(claw=('yes'))))
  def guess_bear(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Bear")
      print("\t    Fun fact about Bears: There are 8 different species of Bears: North American black bears, brown bears, polar bears, Asiatic black bears, Andean bears, panda bears, sloth bears, and sun bears")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
 
  @Rule (AND(Animal(start =('yes')), Animal(warmblooded=('yes')), Animal(mammal=('yes')), Animal(jungle=('yes')), Animal(fur=('yes')), Animal(claw=('yes'))))
  def guess_lion(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Lion")
      print("\t    Fun fact about Lions: Lions can eat up to 40kg of meat in a single meal")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
 
  @Rule (AND(Animal(start =('yes')), Animal(warmblooded=('yes')), Animal(mammal=('yes')), Animal(fur=('yes')), Animal(layEgg=('yes'))))
  def guess_platypus(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Platypus")
      print("\t    Fun fact about Platypuses: Platypuses are biofluorescent, meaning their fur glows a bluish-green hue under ultraviolet (UV) light")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start =('yes')), Animal(warmblooded=('yes')), Animal(mammal=('yes')), Animal(fur=('yes')), Animal(layEgg=('no'))))
  def guess_otter(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Otter")
      print("\t    Fun fact about Otters: Otters have strong teeth and a powerful bite")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('yes')),  Animal(mammal = ('yes')), Animal(fur = ('no')), Animal(ivory = ('no'))))
  def guess_sphynx(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Sphynx cat") 
      print("\t    Fun fact about Sphynx cats: Sphynx cats love their human owners and generally get along with dogs and other cats")    
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")   
      
  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('yes')),  Animal(mammal = ('yes')), Animal(fur = ('no')), Animal(ivory = ('yes'))))
  def guess_elephent(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Elephant") 
      print("\t    Fun fact about Elephents: The African Savanna (Bush) elephant is the world's largest land animal")    
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('yes')),  Animal(mammal = ('no')), Animal(bird = ('yes')), Animal(feather = ('no'))))
  def guess_kiwi(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a kiwi") 
      print("\t    Fun fact about Kiwi bird: Kiwi have the smallest beaks in the world")    
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('yes')), Animal(mammal = ('no')), Animal(bird = ('yes')), Animal(feather = ('yes')),  Animal(fly = ('yes'))))
  def guess_stork(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Stork")
      print("\t    Fun fact about Storks: Storks are carnivorous. They feed on fish, frogs and birds, shellfish, small reptiles and insects")  
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
 
  @Rule (AND(Animal(start = ('yes')), Animal(mammal = ('no')), Animal(warmblooded = ('yes')), Animal(bird = ('yes')), Animal(feather = ('yes')), Animal(fly = ('no'))))
  def guess_ostrich(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is an Ostrich")
      print("\t    Fun fact about Ostrishes: Ostriches are the fastest running birds in the world")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('no')), Animal(coldblooded = ('yes')),  Animal(amphibian = ('no')), Animal(reptile = ('yes')), Animal(layEgg = ('no'))))
  def guess_eyelashViper(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is an Eyelash viper")
      print("\t    Fun fact about Eyelash vipers: Eyelash vipers snakes are ovoviviparous, The female snake retains the fertilized eggs inside her body")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('no')), Animal(coldblooded = ('yes')),  Animal(amphibian = ('no')), Animal(reptile = ('yes')), Animal(shell = ('no')), Animal(layEgg = ('yes'))))
  def guess_crocodile(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Crocodile")
      print("\t    Fun fact about Crocodiles: Crocodiles can go through 4,000 teeth over a lifetime")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('no')), Animal(coldblooded = ('yes')), Animal(amphibian = ('no')), Animal(reptile = ('yes')), Animal(shell = ('yes')), Animal(layEgg = ('yes'))))
  def guess_tortoise(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Tortoise")
      print("\t    Fun fact about Tortoises: Tortoises have been around for over 200 million years. Longer than lizards, birds, mammals, crocodiles and snakes")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('no')), Animal(coldblooded = ('yes')), Animal(amphibian = ('yes')), Animal(tail = ('no')),  Animal(mucus = ('yes'))))
  def guess_frog(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t       The animal is a Frog") 
      print("\t       Fun fact about Frogs: Frogs were the first land animals with vocal cords. Male frogs have vocal sacs which are pouches of skin that fill with air")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('no')), Animal(coldblooded = ('yes')), Animal(amphibian = ('yes')), Animal(tail = ('yes'))))
  def guess_salamander(self):
      print("\n")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
      print("\t    The animal is a Salamander")     
      print("\t    Fun fact about Salmanders: Salamanders are capable of regenerating lost limbs")
      print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

  @Rule (AND(Animal(start = ('yes')), Animal(warmblooded = ('no')), Animal(coldblooded = ('no')), Animal(amphibian =('no')), Animal(reptile = ('no')), Animal(layEgg = ('no'))))
  def guess_fail(self):
      print("\n")
      print("---------- Failed inputs ----------")   
      print("----------Try again :) ----------")  
engine = AnimalGame()
#Prepare the engine for the execution.
engine.reset() 
animal_start = ' '; animal_warmblood = ' '; animal_coldblood = ' '; animal_mammal = ' '; animal_amphibian = ' '; animal_reptile = ' ';  animal_bird = ' '; animal_forest = ' '; animal_jungle = ' '; animal_fur = ' '; animal_feather = ' '; animal_claw = ' '; animal_tail = ' '; animal_fly = ' '; animal_shell = ' '; animal_mucus = ' '; animal_layEgg = ' '; animal_ivory = ' '
#Opening screen
print("\t===================================")
print("\t    < Welcome to the Wildlife >")
print("\t===================================\n")
print("\t    Available animals in our game: ")
print("\t-----------------------------------")
print("\t\t== Bear")
print("\t\t== Lion")
print("\t\t== Elephant")
print("\t\t== Platypus")
print("\t\t== Sphynx cat")
print("\t\t== Otter")
print("\t\t== Ostrich")
print("\t\t== Kiwi")
print("\t\t== Stork")
print("\t\t== Frog")
print("\t\t== Salamander")
print("\t\t== Tortoise")
print("\t\t== Crocodile") 
print("\t\t== Eyelash Viper")
print("\t-----------------------------------\n")

#The gameplay
animal_start = input("Do you want to start the game? (Yes/No) ").lower()
if animal_start =='yes':
  animal_warmblood = input("Is the animal warm-blooded? (Yes/No) ").lower()
  if animal_warmblood == 'yes':
      animal_mammal = input("Is the animal a Mammal? (Yes/No) ").lower()
      if animal_mammal == 'no':
        animal_bird = input("Is the animal a Bird? (Yes/No) ").lower()
        if animal_bird == 'yes':
          animal_feather = input("Does the animal have feather? (Yes/No) ").lower()
          if animal_feather == 'yes':
            animal_fly = input("Can the animal fly? (Yes/No) ").lower()
        else:
          print("\n")
          print("---------- Failed inputs ----------")   
          print("----------Try again :) ----------") 
          quit()  
      else: 
        animal_fur = input("Does the animal have a fur? (Yes/No) ").lower()
        if animal_fur == 'no':
          animal_ivory = input("Does the animal have ivory? (Yes/No) ").lower()
        else:
          animal_claw = input("Does the animal have claws? (Yes/No) ").lower()
          if animal_claw == 'no':
            animal_layEgg = input("Does the animal lay egg? (Yes/No) ").lower()
          else:
            animal_forest = input("Does the animal live in the forest? (Yes/No) ").lower()
            if animal_forest == 'no':
              animal_jungle = input("Does the animal live in the jungle? (Yes/No) ").lower() 
              if animal_jungle == 'no':
                print("\n")
                print("---------- Failed inputs ----------")   
                print("----------Try again :) ----------") 
                quit()  
  else:
    animal_coldblood = input("Is the animal cold-blooded? (Yes/No) ").lower()
    if animal_coldblood == 'no':
          print("\n")
          print("---------- Failed inputs ----------")   
          print("----------Try again :) ----------")   
          quit()
    else:
      animal_amphibian = input("Is the animal an Amphibian? (Yes/No) ").lower()
      if animal_amphibian == 'yes':
        animal_tail = input("Does the animal have a tail? (Yes/No) ").lower()
        if animal_tail == 'no':
         animal_mucus = input("Does the animal have mucus? (Yes/No) ").lower()
         if animal_mucus == 'no':
            print("\n")
            print("---------- Failed inputs ----------")   
            print("----------Try again :) ----------")   
            quit()
      else:
        animal_reptile = input("Is the animal a Reptile? (Yes/No) ").lower()
        if animal_reptile  == 'no':
            print("\n")
            print("---------- Failed inputs ----------")   
            print("----------Try again :) ----------") 
            quit()
        else:
          animal_layEgg = input("does the animal lay egg? (Yes/No) ").lower()
          if animal_layEgg == 'yes':
            animal_shell = input("Does the animal have a shell? (Yes/No) ").lower()

else:
  print("\n")
  print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
  print("\t\t   < Game over >")
  print("\t~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

engine.declare(Animal(start = animal_start), Animal(warmblooded = animal_warmblood), Animal(coldblooded = animal_coldblood), Animal(mammal = animal_mammal), Animal(amphibian = animal_amphibian), Animal(bird = animal_bird), Animal(reptile = animal_reptile), Animal(forest = animal_forest), Animal(jungle = animal_jungle), Animal(fur = animal_fur), Animal(feather = animal_feather), Animal(claw = animal_claw), Animal(tail = animal_tail), Animal(fly = animal_fly), Animal(shell = animal_shell), Animal(mucus = animal_mucus), Animal(layEgg = animal_layEgg), Animal(ivory = animal_ivory)) 
#Run engine
engine.run()

